# Generated by Django 6.0.7 on 2026-09-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('subject', models.CharField(default='General Consultation', max_length=200)),
                ('service_interest', models.CharField(default='Interior & Construction', max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('interior', 'Interior Design'), ('construction', 'Construction')], max_length=20)),
                ('project_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('year', models.CharField(default='2024', max_length=10)),
                ('image_url', models.URLField(max_length=500)),
                ('description', models.TextField()),
                ('area_sqft', models.PositiveIntegerField(default=2500, help_text='Area in Sq. Ft.')),
                ('duration', models.CharField(default='6 Months', max_length=50)),
                ('client_type', models.CharField(default='Private Client', max_length=100)),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('service_type', models.CharField(choices=[('interior', 'Interior Design'), ('construction', 'Construction'), ('both', 'Turnkey (Interior + Construction)')], max_length=20)),
                ('project_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], max_length=20)),
                ('estimated_area', models.PositiveIntegerField(default=1500)),
                ('finish_tier', models.CharField(default='Premium', max_length=50)),
                ('estimated_budget', models.CharField(blank=True, max_length=100)),
                ('timeline', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('interior', 'Interior Design'), ('construction', 'Construction')], max_length=20)),
                ('short_desc', models.TextField()),
                ('icon_name', models.CharField(default='Layers', max_length=50)),
                ('features', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
